trigger:
  branches:
    include:
      - main

variables:
  ACR_NAME: NkDemoProjectacr09
  IMAGE_NAME: hello-aks
  RESOURCE_GROUP: NkDemoProjectRG
  CLUSTER_NAME: NkDemoProjectAks
  NAMESPACE: dev

stages:
- stage: Build
  displayName: 'Build and Push to ACR'
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: 'Build and Push Docker image'
      inputs:
        containerRegistry: '$(ACR_NAME)'
        repository: '$(IMAGE_NAME)'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: |
          v1

- stage: Deploy
  displayName: 'Deploy to AKS'
  dependsOn: Build
  jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName: 'Apply manifests to AKS'
      inputs:
        azureSubscription: '<your-service-connection-name>'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az aks get-credentials --resource-group $(RESOURCE_GROUP) --name $(CLUSTER_NAME) --overwrite-existing
          kubectl apply -f deployment.yaml -n $(NAMESPACE)
          kubectl apply -f service.yaml -n $(NAMESPACE)
          kubectl apply -f ingress.yaml -n $(NAMESPACE)
