name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

env:
  ACR_NAME: NkDemoProjectacr09
  IMAGE_NAME: hello-aks
  RESOURCE_GROUP: NkDemoProjectRG
  CLUSTER_NAME: NkDemoProject-aks-cluster
  NAMESPACE: dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Docker login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
        password: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}  

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push Docker image
      run: |
        IMAGE_TAG=${{ github.run_number }}        
        docker tag $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG $ACR_NAME.azurecr.io/$IMAGE_NAME:latest
        docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:latest

    - name: Set AKS credentials
      run: az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME --overwrite-existing

    - name: Deploy to AKS
      run: |
        kubectl apply -f deployment.yaml -n $NAMESPACE
        kubectl apply -f service.yaml -n $NAMESPACE
        kubectl apply -f ingress.yaml -n $NAMESPACE
